(() => {
  const cfg=window.ZWAP_CONFIG||{};
  const $=id=>document.getElementById(id);
  const status=t=>{$('status').textContent=t};
  const fmt=v=>v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(2);
  const etDate=()=>{const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=k=>parts.find(v=>v.type===k).value;return `${get('year')}-${get('month')}-${get('day')}`};
  const etTime=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit'}).format(d)};
  const sessionId=(()=>{const key='foxchase_zwap_session';let v=localStorage.getItem(key);if(!v){v=crypto.randomUUID().replaceAll('-','');localStorage.setItem(key,v)}return v})();
  let sessions=[];
  const sessionsUrl=cfg.sessionsUrl||(cfg.connectorUrl||'').replace(/\/api\/session$/,'/api/sessions');
  function setupCanvas(id){const c=$(id),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);return{x,w,h}};
  function drawGrid(x,l,t,r,b,lo,hi){x.font='10px sans-serif';for(let i=0;i<=4;i++){const y=t+(b-t)*i/4,v=hi-(hi-lo)*i/4;x.strokeStyle='#252b33';x.beginPath();x.moveTo(l,y);x.lineTo(r,y);x.stroke();x.fillStyle='#8b949e';x.textAlign='right';x.fillText(v.toFixed(2),r-4,y+3)}}
  function drawTimeAxis(x,p,l,r,b){const count=Math.min(6,p.length);x.font='10px sans-serif';x.fillStyle='#8b949e';x.strokeStyle='#30363d';x.textAlign='center';for(let j=0;j<count;j++){const i=Math.round((p.length-1)*j/Math.max(1,count-1)),cx=l+(r-l)*i/Math.max(1,p.length-1);x.beginPath();x.moveTo(cx,b+1);x.lineTo(cx,b+5);x.stroke();x.fillText(etTime(p[i].timestamp),cx,b+17)}}
  function drawPrice(series){const {x,w,h}=setupCanvas('price'),p=series.filter(v=>v.option_close!=null);if(!p.length)return;const l=10,r=w-10,t=10,b=h-38,vals=p.flatMap(v=>[v.option_low??v.option_close,v.option_high??v.option_close]);let lo=Math.min(...vals),hi=Math.max(...vals),pad=Math.max((hi-lo)*.12,.05);lo-=pad;hi+=pad;const X=i=>l+(r-l)*i/Math.max(1,p.length-1),Y=v=>b-(b-t)*(v-lo)/(hi-lo);drawGrid(x,l,t,r,b,lo,hi);drawTimeAxis(x,p,l,r,b);p.forEach((v,i)=>{const o=Number(v.option_open??v.option_close),c=Number(v.option_close),color=c>=o?'#39ff14':'#ff391f',cx=X(i);x.strokeStyle=color;x.beginPath();x.moveTo(cx,Y(Number(v.option_high??c)));x.lineTo(cx,Y(Number(v.option_low??c)));x.stroke();x.fillStyle=color;x.fillRect(cx-2,Y(Math.max(o,c)),4,Math.max(1,Y(Math.min(o,c))-Y(Math.max(o,c))))})}
  function drawZ(series){const {x,w,h}=setupCanvas('z'),p=series.filter(v=>v.ex_z!=null);if(!p.length)return;const l=10,r=w-10,t=10,b=h-38,ref=p.slice(0,30).map(v=>Number(v.ex_z)),lo=Math.min(-2,...ref)-.1,hi=Math.max(2,...ref)+.1,X=i=>l+(r-l)*i/Math.max(1,p.length-1),Y=v=>b-(b-t)*(v-lo)/(hi-lo);drawGrid(x,l,t,r,b,lo,hi);drawTimeAxis(x,p,l,r,b);x.setLineDash([4,4]);x.strokeStyle='#6e7681';[0].forEach(v=>{x.beginPath();x.moveTo(l,Y(v));x.lineTo(r,Y(v));x.stroke()});x.setLineDash([]);x.strokeStyle='#f2cc60';x.lineWidth=2;x.beginPath();p.forEach((v,i)=>i?x.lineTo(X(i),Y(Number(v.ex_z))):x.moveTo(X(i),Y(Number(v.ex_z))));x.stroke()}
  function renderSessions(){const filter=$('regimeFilter').value;const current=$('date').value;const visible=sessions.filter(s=>s.date<etDate()&&(filter==='ALL'||s.regime===filter));const picker=$('sessionPicker');picker.innerHTML=visible.length?visible.map(s=>`<option value="${s.date}" ${s.date===current?'selected':''}>${s.date} · ${s.regime}</option>`).join(''):'<option value="">No cached historical sessions</option>';if(current&&visible.some(s=>s.date===current))picker.value=current}
  async function refreshSessions(){if(!sessionsUrl)return;try{const response=await fetch(sessionsUrl);const result=await response.json();if(response.ok&&Array.isArray(result.sessions)){sessions=result.sessions;renderSessions()}}catch(_) {}}
  async function heartbeat(){if(!cfg.presenceUrl)return;try{await fetch(cfg.presenceUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId})})}catch(_){}}
  async function load(){const date=$('date').value,offset=Number($('offset').value||1);if(!date){status('Choose a date first.');return}if(date>=etDate()){status('Current-day and future data are reserved for live/paywalled access.');return}if(!cfg.connectorUrl||!cfg.computeUrl){status('Local test config is incomplete. Copy config.example.js to config.js.');return}$('load').disabled=true;status('Fetching your Alpaca bars locally…');try{const source=await fetch(`${cfg.connectorUrl}?date=${encodeURIComponent(date)}&offset=${offset}`);const payload=await source.json();if(!source.ok)throw new Error(payload.error||'local connector failed');status('Computing the study…');const headers={'Content-Type':'application/json','X-ZWAP-Session':sessionId};if(cfg.computeToken)headers.Authorization=`Bearer ${cfg.computeToken}`;const response=await fetch(cfg.computeUrl,{method:'POST',headers,body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||'calculation failed');const p=result.series||[];const z=p.filter(v=>v.ex_z!=null);$('contract').textContent=result.option_symbol||'—';$('regime').textContent=result.regime||'—';$('latest').textContent=z.length?fmt(z[z.length-1].ex_z):'warming up';drawPrice(p);drawZ(p);status(`Loaded ${result.option_symbol} · ${p.length} bars · ${result.warmup_bars||0} warm-up bars.`);refreshSessions()}catch(e){status(`Error: ${e.message}`)}finally{$('load').disabled=false}}
  $('date').max=(()=>{const d=new Date(`${etDate()}T00:00:00Z`);d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)})();
  $('regimeFilter').addEventListener('change',renderSessions);
  $('sessionPicker').addEventListener('change',()=>{if($('sessionPicker').value){$('date').value=$('sessionPicker').value;load()}});
  $('load').addEventListener('click',load);
  document.querySelectorAll('.strike-button').forEach(button=>button.addEventListener('click',()=>{
    const next=button.dataset.offset!==undefined?Number(button.dataset.offset):Number($('offset').value||0)+Number(button.dataset.step||0);
    $('offset').value=Math.max(-10,Math.min(10,next));
    if($('date').value) load();
  }));
  refreshSessions();heartbeat();setInterval(heartbeat,30000);addEventListener('resize',()=>{});
})();
